### ISSUE TITLE
Get the correct image from the product

### ISSUE THREAD

**Issue by mridang** [Nosto/nostotagging#22]
Currently we use the method `getFormatedName` to get the image and this works fine in most cases but we've seen some issues.

The method used the type passed to it e.g. `large` and appends the name of the theme to it e.g. `large_default`.

A merchant was using the theme called "Alysum" and this method returned `large_Alysum` but this image-type doesn't exist.

Each theme has the right to define custom images in the `theme.xml` and in this case the theme had registered `large_alysum` but the method returns `large_Alysum`.

**Comment by kryysler** [comment]
Merged to develop
