### ISSUE TITLE
Support the correct cart/order tagging to parent-child products

### ISSUE THREAD

**Issue by romainsassareu** [Nosto/nostotagging#42]
Context, as discussed with Mridang. 

http://www.beauxarts.fr/aquarelle-winsor-et-newton-extra-fine/13071-aquarelle-winsor-et-newton-demi-godet.html?nostodebug=true

#1 / One mother product with around 30 child variations with different prices. 
#2 / When several child are added to cart, we retarget child products separately in an AC e-mail instead of grouping them.

![beauxarts](https://cloud.githubusercontent.com/assets/10031826/7806619/68855f9a-0383-11e5-823d-40a47f59f0ca.jpg)

**Comment by mridang** [comment]
As discussed, the DPDP will always list out the details of the parent product and on the cart page, the attribute values will be pivoted and concatenated with a slash. e.g. "Paint (Yellow / 30ml).

**Comment by romainsassareu** [comment]
Released in the upcoming version then?

Best,

Romain Sassareu

E-commerce Specialist | Nosto Solutions Ltd
M: +49 157 553 051 89 | Skype: romain.nosto

Nosto awarded ‘Supplier of the year 2014’ in the Nordic eCommerce Awards
<http://www.nordicecommercesummit.se/award/> !



www.nosto.com

Nosto Solutions GmbH | Winsstraße 62/63  | 10405 Berlin
Managing Directors: Juha Valvanne, Matti Rönkkö,
Local court: Berlin-Charlottenburg,
Commercial register number : 152111 B

**Comment by kryysler** [comment]
Added in feature/milestone-2.4.0
