### ISSUE TITLE
Unable to show the admin section when the adminCss is missing

### ISSUE THREAD

**Issue by mridang** [Nosto/nostotagging#46]
https://github.com/Nosto/nostotagging/blob/master/nostotagging.php#L455 fails when some backend controller is missing the method.

The merchant encountered a blank page when using the module Blank page when selecting the module "Chronossimo"

```
Notice: Constant _PS_DEBUG_SQL_ already defined in /home/naturosphere/www/config/config.inc.php on line 9 Fatal error: Call to undefined method AdminChronossimo::addCss() in /home/naturosphere/www/modules/nostotagging/nostotagging.php on line 455
```

**Comment by kryysler** [comment]
Fixed in version 2.4.2
